%%  Young vs. adult anti-saccade cue-aligned (Gamma cue tuning)
inputs = {...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 0).*(neuron_tbl.cue_gamma == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 0).*(neuron_tbl.cue_gamma == 0)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 1).*(neuron_tbl.cue_gamma == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 1).*(neuron_tbl.cue_gamma == 0)), :), ...
    };
pev_plot(inputs, t_bins_cue, {'Adolescent w/ Gamma-tuning', 'Adolescent w/o Gamma-tuning', 'Adult w/ Gamma-tuning', 'Adult w/o Gamma-tuning'}, {'r', [0.6,0.2,0.2], 'b', [0.2, 0.2, 0.6]})
xlabel('Time from saccadic onset (s)')
title('PEV of neurons by cue period gamma tuning (anti-saccade)')
fig_name = 'pev_gamma_cue_as_sac_aligned';
print(gcf, fullfile(project_dir, fig_lib, fig_name), '-dpng', '-r400');
%%  Young vs. adult anti-saccade cue-aligned (Gamma delay tuning)
inputs = {...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 0).*(neuron_tbl.delay_gamma == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 0).*(neuron_tbl.delay_gamma == 0)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 1).*(neuron_tbl.delay_gamma == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 1).*(neuron_tbl.delay_gamma == 0)), :), ...
    };
pev_plot(inputs, t_bins_cue, {'Adolescent w/ Gamma-tuning', 'Adolescent w/o Gamma-tuning', 'Adult w/ Gamma-tuning', 'Adult w/o Gamma-tuning'}, {'r', [0.6,0.2,0.2], 'b', [0.2, 0.2, 0.6]})
xlabel('Time from saccadic onset (s)')
title('PEV of neurons by delay period gamma tuning (anti-saccade)')
fig_name = 'pev_gamma_delay_as_sac_aligned';
print(gcf, fullfile(project_dir, fig_lib, fig_name), '-dpng', '-r400');
%%  Young vs. adult anti-saccade cue-aligned (Beta cue tuning)
inputs = {...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 0).*(neuron_tbl.cue_beta == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 0).*(neuron_tbl.cue_beta == 0)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 1).*(neuron_tbl.cue_beta == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 1).*(neuron_tbl.cue_beta == 0)), :), ...
    };
pev_plot(inputs, t_bins_cue, {'Adolescent w/ Beta-tuning', 'Adolescent w/o Beta-tuning', 'Adult w/ Beta-tuning', 'Adult w/o Beta-tuning'}, {'r', [0.6,0.2,0.2], 'b', [0.2, 0.2, 0.6]})
xlabel('Time from saccadic onset (s)')
title('PEV of neurons by cue period beta tuning (anti-saccade)')
fig_name = 'pev_beta_cue_as_sac_aligned';
print(gcf, fullfile(project_dir, fig_lib, fig_name), '-dpng', '-r400');
%%  Young vs. adult anti-saccade cue-aligned (Beta delay tuning)
inputs = {...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 0).*(neuron_tbl.delay_beta == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 0).*(neuron_tbl.delay_beta == 0)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 1).*(neuron_tbl.delay_beta == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 2).*(neuron_tbl.aged == 1).*(neuron_tbl.delay_beta == 0)), :), ...
    };
pev_plot(inputs, t_bins_cue, {'Adolescent w/ Beta-tuning', 'Adolescent w/o Beta-tuning', 'Adult w/ Beta-tuning', 'Adult w/o Beta-tuning'}, {'r', [0.6,0.2,0.2], 'b', [0.2, 0.2, 0.6]})
xlabel('Time from saccadic onset (s)')
title('PEV of neurons by delay period beta tuning (anti-saccade)')
fig_name = 'pev_beta_delay_as_sac_aligned';
print(gcf, fullfile(project_dir, fig_lib, fig_name), '-dpng', '-r400');