%%  Young vs. adult ODR cue-aligned
inputs = {neuron_pev_cue(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 0)), :), ...
    neuron_pev_cue(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 1)), :)};
pev_plot(inputs, t_bins_cue, {'Adolescent', 'Adult'}, {'r', 'b'})
xlabel('Time from cue onset (s)')
title('PEV of neurons at different stages (ODR)')
fig_name = 'pev_stage_odr_cue_aligned';
print(gcf, fullfile(project_dir, fig_lib, fig_name), '-dpng', '-r400');
%%  Young vs. adult ODR sac-aligned
inputs = {neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 0)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 1)), :)};
pev_plot(inputs, t_bins_sac, {'Adolescent', 'Adult'}, {'r', 'b'})
xlabel('Time from saccadic onset (s)')
title('PEV of neurons at different stages (ODR)')
fig_name = 'pev_stage_odr_sac_aligned';
print(gcf, fullfile(project_dir, fig_lib, fig_name), '-dpng', '-r400');
%%  Young vs. adult ODR sac-aligned (Gamma cue tuning)
inputs = {...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 0).*(neuron_tbl.cue_gamma == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 0).*(neuron_tbl.cue_gamma == 0)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 1).*(neuron_tbl.cue_gamma == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 1).*(neuron_tbl.cue_gamma == 0)), :), ...
    };
pev_plot(inputs, t_bins_sac, {'Adolescent w/ Gamma-tuning', 'Adolescent w/o Gamma-tuning', 'Adult w/ Gamma-tuning', 'Adult w/o Gamma-tuning'}, {'r', [0.6,0.2,0.2], 'b', [0.2, 0.2, 0.6]})

%%  Young vs. adult ODR sac-aligned (Gamma delay tuning)
inputs = {...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 0).*(neuron_tbl.delay_gamma == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 0).*(neuron_tbl.delay_gamma == 0)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 1).*(neuron_tbl.delay_gamma == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 1).*(neuron_tbl.delay_gamma == 0)), :), ...
    };
pev_plot(inputs, t_bins_sac, {'Adolescent w/ Gamma-tuning', 'Adolescent w/o Gamma-tuning', 'Adult w/ Gamma-tuning', 'Adult w/o Gamma-tuning'}, {'r', [0.6,0.2,0.2], 'b', [0.2, 0.2, 0.6]})
%%  Young vs. adult ODR sac-aligned (Beta cue tuning)
inputs = {...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 0).*(neuron_tbl.cue_beta == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 0).*(neuron_tbl.cue_beta == 0)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 1).*(neuron_tbl.cue_beta == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 1).*(neuron_tbl.cue_beta == 0)), :), ...
    };
pev_plot(inputs, t_bins_sac, {'Adolescent w/ Beta-tuning', 'Adolescent w/o Beta-tuning', 'Adult w/ Beta-tuning', 'Adult w/o Beta-tuning'}, {'r', [0.6,0.2,0.2], 'b', [0.2, 0.2, 0.6]})
%%  Young vs. adult ODR sac-aligned (Beta delay tuning)
inputs = {...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 0).*(neuron_tbl.delay_beta == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 0).*(neuron_tbl.delay_beta == 0)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 1).*(neuron_tbl.delay_beta == 1)), :), ...
    neuron_pev_sac(find(needed_neuron.*(neuron_tbl.task_id == 1).*(neuron_tbl.aged == 1).*(neuron_tbl.delay_beta == 0)), :), ...
    };
pev_plot(inputs, t_bins_sac, {'Adolescent w/ Beta-tuning', 'Adolescent w/o Beta-tuning', 'Adult w/ Beta-tuning', 'Adult w/o Beta-tuning'}, {'r', [0.6,0.2,0.2], 'b', [0.2, 0.2, 0.6]})

